package com.olo.annotations;

import com.fasterxml.jackson.annotation.JsonInclude;

import java.util.List;

/**
 * Serializable feature metadata for JSON generation and bootstrap loading.
 * Generated by the annotation processor from {@link OloFeature}.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class FeatureInfo {

    private final String name;
    private final String phase;
    private final List<String> applicableNodeTypes;
    private final String className;

    public FeatureInfo(String name, String phase, List<String> applicableNodeTypes, String className) {
        this.name = name;
        this.phase = phase;
        this.applicableNodeTypes = applicableNodeTypes;
        this.className = className;
    }

    public String getName() { return name; }
    public String getPhase() { return phase; }
    public List<String> getApplicableNodeTypes() { return applicableNodeTypes; }
    public String getClassName() { return className; }
}
